/*
 * Skeleton code provided by: Professor Yong Guan.
 * Author : Jawad M Rahman
 * This is the client side code for an RPC connection. The user is
 * given seven choices and according to the user's choice, functions
 * are called in the server and the value is returned here.
 */
#include	<stdio.h>
#include 	<string.h>
#include 	<time.h>
#include 	<sys/types.h>
#include	<rpc/rpc.h>	/* standard RPC include file */
#include	"date.h"	/* this file is generated by rpcgen */

#define MAX_LEN 100
long get_response(void);

/* User input */
long get_response()
{
    long choice;
    printf("----------------------------------------------------\n");
    printf("\nPlease choose any of the following from the menu: \n");
    printf("1. Date\n");
    printf("2. Time\n");
    printf("3. Both Date and Time\n");
    printf("4. CPU Usage\n");
    printf("5. Memory Usage\n");
    printf("6. Load Procs Per Min\n");
    printf("7. Swap Usage\n");
    printf("8. List of user names\n");
    printf("9. Quit\n");
    printf("----------------------------------------------------\n");
    scanf("%ld",&choice);
    return(choice);
}

main(int argc, char **argv)
{
    CLIENT  *cl;        /* RPC handle */
    char    *server;
    char    **sresult;  /* return value from the different functions called based on the user input  */
    char    s[MAX_LEN];    /* character array to hold output */
    long    response;  /* user response */
    long    *lresult;    /* pointer to user response */

    if (argc != 2) {
        fprintf(stderr, "usage: %s hostname\n", argv[0]);
        exit(1);
    }
    server = argv[1];
    lresult = (&response);
    /*
     * Create the client "handle."
     */
    cl = clnt_create(server, DATE_PROG, DATE_VERS, "udp");
    if (cl == NULL) {
        clnt_pcreateerror(server);
        exit(2);
    }
    response = get_response();

    /*
     * In this portion, according to the user's response,
     * we call the functions used to find the desired info
     * and if for some reason the program fails to deliver it,
     * an error is reported
     * All these functions are programmed/written in the server file
     */

    if(response == 9) {
      system("pkill server");
    }
    while(response != 9) {
        double *stats;
        switch(response) {
          case 1: case 2: case 3: case 7: case 8:
            if ((sresult = date_1(lresult, cl)) == NULL) {
                clnt_perror(cl, server);
                exit(3);
            }
          break;

          case 4:
            stats = cpu_1(NULL,cl);
            if (stats == NULL) {
                clnt_perror(cl, server);
                exit(3);
            }
            printf("\nThe current average CPU usage is: %.5lf\n", *stats);
          break;

          case 5:
            stats = memory_1(NULL,cl);
            if (stats == NULL) {
                clnt_perror(cl, server);
                exit(3);
            }
            printf("\nThe percentage of memory being used is %.2lf\n", *stats);
          break;

          case 6:
          stats = process_1(NULL,cl);
            if (stats == NULL) {
                clnt_perror(cl, server);
                exit(3);
            }
            printf("\nThe load average of one minute is %.4lf\n", *stats);
          break;
      }
      if(response == 1 || response == 2 || response == 3 || response ==7 || response == 8){
        if (response ==8) {
          printf("%s\n", "The first letters of each of the usernames are: ");
        }
        	printf("  %s\n", *sresult);
      }
	response = get_response();
    }
    clnt_destroy(cl);		/* terminate the handle */
    exit(0);
}
