/*
 * Skeleton code provided by: Professor Yong Guan.
 * Author : Jawad M Rahman
 * This is the server side code for an RPC connection. In short,
 * it runs the functions requested by the client and returns the required values.
 */
#include <rpc/rpc.h>	/* standard RPC include file */
#include <time.h>
#include <sys/types.h>
#include "date.h"	/* this file is generated by rpcgen */
#include <stdlib.h>
#include <stdio.h>
#include <linux/kernel.h>
#include <sys/sysinfo.h>
#include <pwd.h>
#define MAX_LEN 100
/*
 * Returns the binary date and time, swap usage and list of users.
 */
char ** date_1(long *option)
{
    struct tm *timeptr; /* Pointer to time structure      */
    time_t clock;       /* Clock value (in secs)          */
    static char *ptr;   /* Return string                  */
    static char err[] = "Invalid Response \0";
    static char s[MAX_LEN];
    const char *strings[MAX_LEN];

    struct sysinfo info;
    sysinfo(&info);
    static unsigned long swapUsage;

    clock = time(0);
    timeptr = localtime(&clock);

    struct passwd *pwStruct;
    FILE* passwd_file;
    int i =0;
    switch(*option)
        {
        case 1: strftime(s,MAX_LEN,"%A, %B %d, %Y",timeptr);
                ptr=s;
                break;

        case 2: strftime(s,MAX_LEN,"%T",timeptr);
                ptr=s;
                break;

        case 3: strftime(s,MAX_LEN,"%A, %B %d, %Y - %T",timeptr);
                ptr=s;
                break;

        case 7: /* For total swap space size */
          swapUsage = info.totalswap -info.freeswap;
          sprintf(s, "Total swap usage is %.9lf",swapUsage*1.0);
          ptr=s;
          break;

        case 8:
          passwd_file = fopen("/etc/passwd","r");
          while ((pwStruct = fgetpwent(passwd_file))!=NULL) {
            s[i] = *pwStruct->pw_name;
            printf("The username is %s\n", pwStruct->pw_name);
            i++;
          }
          ptr = s;
          printf("%s\n", "---------- END OF THE LIST-----------");
          fclose(passwd_file);
          break;

        default: ptr=err;
                 break;
        }
    return(&ptr);
}


/* Returns the percentage of memory being used */

double * memory_1(void){
  struct sysinfo info;
  sysinfo(&info);
  unsigned long memUsage;
  static double usagePercentage;
  memUsage = info.totalram - info.freeram;
  usagePercentage = ((memUsage*1.0)/(info.totalram*1.0))*100.0;
  return(&usagePercentage);
}

/* Returns the CPU usage statistics.
 * For more information, the following web-page explains the calculation clearly:
 * https://supportcenter.checkpoint.com/supportcenter/portal?eventSubmit_doGoviewsolutiondetails=&solutionid=sk65143
 * I have followed it to some extent - I have only used user, nice, system processes and idle.
*/

double * cpu_1(void){
   static double cpu_usage;
   long double arr[8];
   FILE* cpu_file;
   cpu_file = fopen("/proc/stat","r");
   if (cpu_file == NULL) {
      printf("ERROR: Unable open file");
      exit(1);
   }
   //In the first line, the numbers are the sum of the numbers of the rows beneath them
   fscanf(cpu_file, "%*s %Lf %Lf %Lf %Lf %Lf",&arr[0],&arr[1],&arr[2],&arr[3],&arr[4]);
   fclose(cpu_file);
  //total cpu usage = (user + nice + system)/(user + nice + system + idle)
   cpu_usage = ((arr[1]+arr[2]+arr[3]) / (arr[1]+arr[2]+arr[3]+arr[4]))* 100.0;
   return(&cpu_usage);
}

/* Returns the load average of one minute */

double * process_1(void){
  static double load[3];
  if(getloadavg(load, 3) != -1){
    return (&load[0]);
  }
}
